### ISSUE TITLE
Manage IoT Data

### ISSUE THREAD

**Issue by PetraHrabakova** [garbage-group/SEP4-Cloud#44]
Parent Epic: [Manage Bins](https://github.com/garbage-group/SEP4/issues/3)

## Description
- Get temperature data from IoT - if the data is old, fetch it from IoT device, otherwise return from DB - same logic as getHumidity
- Get level data from IoT - if the data is old, fetch it from IoT device, otherwise return from DB - same logic as getHumidity
- Get status from IoT - send request to the IoT device and return it to the frontend

## Subtasks
- [x] #46 
- [x] #47 
- [x] #53 
- [x] #58 

## Definition of Done
- [x] Cloud returns the current temperature data to the frontend
- [x] Cloud returns the current fill level data to the frontend
- [x] IoT device is able to connect to the backend app deployed on the cloud
- [x] Cloud returns the IoT's status to the frontend
