### ISSUE TITLE
Manage Garbage Collectors - Backend (CRUD)

### ISSUE THREAD

**Issue by PetraHrabakova** [garbage-group/SEP4-Cloud#62]
Parent Epic: [Manage Garbage Collectors]()

## Description
- CRUD for Manage Garbage Collectors 

## Subtasks
- [x] #63 
- [x] #73 
- [x] #70 
- [x] #71 

## Definition of Done
- [x] The system can create a garbage collector
- [x] The system can read one or multiple garbage collectors
- [x] The system can update a garbage collector
- [x] The system can delete a garbage collector
