### ISSUE TITLE
Activity Diagram CRUD Bin

### ISSUE THREAD

**Issue by martin-vlacil** [garbage-group/SEP4-Cloud#64]
### Tasks
- [x] Create Bins AD
- [x] Read Bins AD
- [x] Update Bins AD
- [x] Delete Bins AD
