### ISSUE TITLE
TO-DO list

### ISSUE THREAD

**Issue by martin-vlacil** [garbage-group/SEP4-Cloud#72]
### Tasks
- [x] setup Azure postgres database
- [x] get humidity by ID 2 gives same value as ID 1
- [x] Consider asynchronous programming
- [x] #26 
- [x] #78 
- [x] #86 
- [x] #88 
- [x] Consider setting up report document, where we can note anything that "we will discuss further in the report" -> It is called "Report content ideas" in Cloud folder in Teams
- [x] reconsider visibility modifiers in code
- [x] check if interface should have all private helper methods
- [x] saveHumidityByBinId() in BinService finalizes the flow as save(bin), it would be better if it saved the humidity instead
- [x] #89 
- [x] Discuss the use of Complex data types over simple types (Double over double)
- [x] make dto converter static
- [x] #101 
- [x] Some dtos are repeating (update DTO with other dtos)
- [x] Https requests contain some parameters multiple times (id in the parameter which can be found in the body)
- [x] API security issues - you can technically meddle with the database if youre logged in and know the api address and you are stupid
- [x] fix api endpoint mappings in bincontroller 
- [x] usercontroller has both interface and implementation, make sure authentication is called through interface
- [x] discuss repeating dto classes
- [x] is municipality worker in jwt stuff case sensitive?
- [x] Discuss the option of having enums for roles in backend code
