### ISSUE TITLE
Process received IoT Data

### ISSUE THREAD

**Issue by martin-vlacil** [garbage-group/SEP4-Cloud#9]
Parent Epic: [Receive and Store IoT Data](https://github.com/orgs/garbage-group/projects/5/views/4?pane=issue&itemId=43720500)

## Description
- Receiving data from IoT in predefined format (as per Interfacing contract) via TCP
- Storing it in database
- Providing REST API endpoint for frontend webapp

## Subtasks
- [x] #11 
- [x] #17 
- [x] #13 
- [x] #14 
- [x] #20 
- [x] #26 
- [x] #28 
- [x] #33 

## Definition of Done
- [x] Communication between IoT - API - Frontend is established and tested
- [x] CI/CD is setup using GitHub Actions (Code is pushed only if the tests pass, Build Rest API as Docker Image)
- [ ] Test coverage report covers 100% and all unit tests pass succesfully

**Comment by tomas-chmelik** [comment]
![Image](https://github.com/garbage-group/SEP4-Cloud/assets/132270259/11c114f9-d9c7-43dc-9e41-03247b48d077)

**Comment by PetraHrabakova** [comment]
Assignment from last semester which includes the folder structure, annotation used by springboot for classes, etc.

[Assignment2.zip](https://github.com/garbage-group/SEP4-Cloud/files/13266844/Assignment2.zip)

**Comment by tomas-chmelik** [comment]
@garbage-group/cloud We agreed to update our tasks before Sunday's scrum masters meeting

**Comment by suhani-pandey** [comment]
created Rest endpoint to get humidity, updated service class, model class, controller class and repository class but cannot push because of some github permission issues.
